// Database types - will be auto-generated by Supabase CLI
// For now, manually defining the schema structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string
          level: 'Beginner' | 'Intermediate' | 'Advanced'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          name: string
          level: 'Beginner' | 'Intermediate' | 'Advanced'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string
          level?: 'Beginner' | 'Intermediate' | 'Advanced'
          created_at?: string
          updated_at?: string
        }
      }
      lessons: {
        Row: {
          id: number
          title: string
          description: string
          duration: string
          category: string
          module: string
          required_level: 'Beginner' | 'Intermediate' | 'Advanced'
          content: Json
          video_url: string | null
          resources: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          title: string
          description: string
          duration: string
          category: string
          module: string
          required_level: 'Beginner' | 'Intermediate' | 'Advanced'
          content: Json
          video_url?: string | null
          resources: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          title?: string
          description?: string
          duration?: string
          category?: string
          module?: string
          required_level?: 'Beginner' | 'Intermediate' | 'Advanced'
          content?: Json
          video_url?: string | null
          resources?: Json
          created_at?: string
          updated_at?: string
        }
      }
      progress: {
        Row: {
          id: string
          user_id: string
          lesson_id: number
          completed: boolean
          completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          lesson_id: number
          completed?: boolean
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          lesson_id?: number
          completed?: boolean
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      notes: {
        Row: {
          id: string
          user_id: string
          lesson_id: number
          content: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          lesson_id: number
          content: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          lesson_id?: number
          content?: string
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          user_id: string
          name: string
          modules: Json
          connections: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          modules: Json
          connections: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          modules?: Json
          connections?: Json
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_level: 'Beginner' | 'Intermediate' | 'Advanced'
    }
  }
}
